import type { District, Gang, GangId, ProductDef, ProductId } from "@/game/types";

export const PRODUCTS: Record<ProductId, ProductDef> = {
  dust: {
    id: "dust",
    name: "Yellow Dust",
    blurb: "Fast, cheap, and every block will take it.",
    heat: 0.42,
    volume: 1,
    markup: 2.4,
    baseWholesale: 70,
  },
  velvet: {
    id: "velvet",
    name: "Velvet",
    blurb: "Club money. The night pays, then it talks.",
    heat: 0.8,
    volume: 0.72,
    markup: 2.65,
    baseWholesale: 190,
  },
  ice: {
    id: "ice",
    name: "Black Ice",
    blurb: "Tiny bags, heavy cash, and heat that sticks.",
    heat: 1.55,
    volume: 0.46,
    markup: 2.7,
    baseWholesale: 440,
  },
  grow: {
    id: "grow",
    name: "Glass Grow",
    blurb: "Slow, steady, and almost polite.",
    heat: 0.28,
    volume: 1,
    markup: 2.35,
    baseWholesale: 42,
  },
};

export const PRODUCT_IDS: ProductId[] = ["dust", "velvet", "ice", "grow"];

export const GANG_IDS: GangId[] = ["vultures", "lanterns", "saints", "cobras"];

type DistrictSeed = Omit<
  District,
  "owner" | "defense" | "corners" | "loyalty" | "stationMuscle" | "stationDealers" | "focus"
> & { owner: District["owner"]; defense: number };

const SEEDS: DistrictSeed[] = [
  {
    id: "glass",
    name: "Glass Mile",
    short: "GLASS",
    blurb: "Old money and new vices. Pays like a mint and talks to the police.",
    col: 0,
    row: 0,
    wealth: 1.62,
    heatMod: 1.45,
    lab: false,
    demand: { dust: 22, velvet: 74, ice: 96, grow: 18 },
    owner: "neutral",
    defense: 18,
  },
  {
    id: "cathedral",
    name: "Cathedral Ward",
    short: "CATH",
    blurb: "Choirs, charities, and envelopes that never see a ledger.",
    col: 1,
    row: 0,
    wealth: 1.32,
    heatMod: 1.12,
    lab: false,
    demand: { dust: 18, velvet: 42, ice: 78, grow: 28 },
    owner: "neutral",
    defense: 15,
  },
  {
    id: "lantern",
    name: "Lantern Row",
    short: "LANTERN",
    blurb: "Tea houses, back rooms, and the Lanterns' home block.",
    col: 2,
    row: 0,
    wealth: 1.22,
    heatMod: 1.05,
    lab: false,
    demand: { dust: 30, velvet: 88, ice: 58, grow: 24 },
    owner: "lanterns",
    defense: 20,
  },
  {
    id: "neon",
    name: "Neon Strip",
    short: "NEON",
    blurb: "All-night money. All-night heat. Nobody here sleeps clean.",
    col: 3,
    row: 0,
    wealth: 1.48,
    heatMod: 1.5,
    lab: false,
    demand: { dust: 28, velvet: 100, ice: 52, grow: 12 },
    owner: "neutral",
    defense: 16,
  },
  {
    id: "rail",
    name: "Railspine",
    short: "RAIL",
    blurb: "Every shipment in the city changes trains here.",
    col: 0,
    row: 1,
    wealth: 1.02,
    heatMod: 1.02,
    lab: false,
    demand: { dust: 72, velvet: 48, ice: 34, grow: 58 },
    owner: "neutral",
    defense: 12,
  },
  {
    id: "market",
    name: "Market Spine",
    short: "MARKET",
    blurb: "The bazaar buys anything if the price is even close.",
    col: 1,
    row: 1,
    wealth: 1.18,
    heatMod: 0.98,
    lab: false,
    demand: { dust: 84, velvet: 62, ice: 40, grow: 76 },
    owner: "neutral",
    defense: 13,
  },
  {
    id: "cobra",
    name: "Cobra Heights",
    short: "COBRA",
    blurb: "Hill houses, party basements, Cobras on the corners.",
    col: 2,
    row: 1,
    wealth: 1.08,
    heatMod: 0.96,
    lab: false,
    demand: { dust: 40, velvet: 78, ice: 36, grow: 70 },
    owner: "cobras",
    defense: 20,
  },
  {
    id: "sinks",
    name: "The Sinks",
    short: "SINKS",
    blurb: "Flood wards. Cheap hands, a buried lab, no officials.",
    col: 3,
    row: 1,
    wealth: 0.7,
    heatMod: 0.74,
    lab: true,
    demand: { dust: 58, velvet: 18, ice: 10, grow: 92 },
    owner: "neutral",
    defense: 10,
  },
  {
    id: "iron",
    name: "Ironworks",
    short: "IRON",
    blurb: "Furnaces, night shifts, and the Saints' house.",
    col: 0,
    row: 2,
    wealth: 0.82,
    heatMod: 0.86,
    lab: true,
    demand: { dust: 88, velvet: 16, ice: 12, grow: 64 },
    owner: "saints",
    defense: 22,
  },
  {
    id: "hollow",
    name: "Hollow Docks",
    short: "HOLLOW",
    blurb: "Your water. Cranes, containers, and a lab that still runs.",
    col: 1,
    row: 2,
    wealth: 0.86,
    heatMod: 0.8,
    lab: true,
    demand: { dust: 94, velvet: 26, ice: 18, grow: 68 },
    owner: "player",
    defense: 24,
  },
  {
    id: "blackwater",
    name: "Blackwater",
    short: "WATER",
    blurb: "South slips. Easy ground if you get there first.",
    col: 2,
    row: 2,
    wealth: 0.78,
    heatMod: 0.8,
    lab: false,
    demand: { dust: 90, velvet: 20, ice: 14, grow: 72 },
    owner: "neutral",
    defense: 11,
  },
  {
    id: "vulture",
    name: "Vulture Yard",
    short: "YARD",
    blurb: "Scrap, smoke, and Harlan Voss's nest.",
    col: 3,
    row: 2,
    wealth: 0.74,
    heatMod: 0.78,
    lab: false,
    demand: { dust: 76, velvet: 14, ice: 10, grow: 84 },
    owner: "vultures",
    defense: 20,
  },
];

export function makeDistricts(): District[] {
  return SEEDS.map((seed) => ({
    ...seed,
    demand: { ...seed.demand },
    corners: seed.owner === "player" ? 1 : seed.owner === "neutral" ? 0 : 1,
    loyalty: seed.owner === "player" ? 74 : 0,
    stationMuscle: seed.owner === "player" ? 2 : 0,
    stationDealers: seed.owner === "player" ? 2 : 0,
    focus: "auto",
  }));
}

export function makeGangs(): Record<GangId, Gang> {
  return {
    vultures: {
      id: "vultures",
      name: "The Vultures",
      tag: "VULT",
      boss: "Harlan Voss",
      blurb: "Scrapyard carrion. They take what the city drops.",
      portrait: "/art/voss.jpg",
      muscle: 10,
      cash: 8000,
      relation: -8,
      truceWeeks: 0,
      alive: true,
      home: "vulture",
      aggression: 0.62,
    },
    lanterns: {
      id: "lanterns",
      name: "The Lanterns",
      tag: "LANT",
      boss: "Madam Shao",
      blurb: "Quiet rooms, perfect books, long memory.",
      portrait: "/art/shao.jpg",
      muscle: 12,
      cash: 14000,
      relation: -6,
      truceWeeks: 0,
      alive: true,
      home: "lantern",
      aggression: 0.4,
    },
    saints: {
      id: "saints",
      name: "Iron Saints",
      tag: "SAINT",
      boss: "Viktor Molch",
      blurb: "Mill blood. They share a fence with your docks.",
      portrait: "/art/molch.jpg",
      muscle: 13,
      cash: 11000,
      relation: -16,
      truceWeeks: 0,
      alive: true,
      home: "iron",
      aggression: 0.58,
    },
    cobras: {
      id: "cobras",
      name: "The Cobras",
      tag: "COBRA",
      boss: "Dante Peck",
      blurb: "Heights parties, basement counts, fast tempers.",
      portrait: "/art/peck.jpg",
      muscle: 11,
      cash: 10000,
      relation: -10,
      truceWeeks: 0,
      alive: true,
      home: "cobra",
      aggression: 0.52,
    },
  };
}

export const WIN_BLOCKS = 8;
export const WIN_WORTH = 350_000;
export const WIN_RESPECT = 55;
